alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: heman-talent-cicd-lab
      match:
        path:
          prefix: /
name: goldfish-app
region: ams
services:
  - health_check:
      http_path: /
    http_port: 80
    image:
      registry: heman
      registry_type: GHCR
      repository: talent-cicd-lab
      tag: latest
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: heman-talent-cicd-lab
